name: Find license compliance and security issues

on:
  schedule:
    - cron: '0 0 * * *' # At the end of every day
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fossa:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run FOSSA scan
        uses: fossas/fossa-action@v1.3.1
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}

      - name: Run FOSSA test
        uses: fossas/fossa-action@v1.3.1
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          run-tests: true
